//! EP-06 (M1) — the node step that makes the parko model allow-list a **signed
//! fact** end to end: verified Uptane `targets` metadata → an emitted
//! `KIRRA_MODEL_ALLOWLIST(_STRICT)` env file the co-located parko process
//! launches under.
//!
//! This is the non-test consumer of `kirra_release_token::model_targets` (the
//! WP-24 projection helpers) and the first *node-side* composition of the whole
//! chain:
//!
//! ```text
//!   UptaneTrustStore (durable root + rollback floor, WP-14)
//!     → uptane::verify_update (role separation / freshness / rollback /
//!       no-mix-and-match, WP-13)
//!       → model_targets::model_allowlist_env_value (signed digest projection)
//!         → an ATOMICALLY-written env file (systemd `EnvironmentFile=`)
//! ```
//!
//! Fail-closed properties:
//! - no trust state, a tampered trust file, a bad signature, an expired or
//!   rolled-back manifest → `Err`, and the CALLER MUST NOT write any file
//!   (the CLI exits non-zero with the previous env file untouched);
//! - the emitted file ALWAYS sets `KIRRA_MODEL_ALLOWLIST_STRICT=1`. Without
//!   strict, an EMPTY allow-list means parko enforcement is OFF — so an empty
//!   signed manifest would silently fail OPEN. With strict pinned in the same
//!   emitted artifact, "the manifest authorizes nothing" is deny-every-model,
//!   exactly the deny-by-default composition `model_targets` documents;
//! - on success the trust store's rollback floor is advanced (durably) BEFORE
//!   the env text is handed back, so a later replay of this same metadata —
//!   or anything older — is refused (`RollbackAttempt`).
//!
//! The metadata arrives as a [`ModelMetadataBundle`] — one JSON document
//! carrying the three role metadatas + signatures. HOW it lands on the node
//! (file drop, `curl`, the full EP-13 repo client) is the transport's concern;
//! this module verifies bytes it is handed and never trusts the carrier.

use kirra_release_token::model_targets::model_allowlist_env_value;
use kirra_release_token::uptane::{verify_update, VerifiedUpdate};

use crate::uptane_trust::{TrustStoreError, UptaneTrustStore};

/// The metadata set a repository publishes for the model allow-list: the three
/// non-root roles + their signatures, as one JSON document. The `targets`
/// entries ARE the authorized model artifacts (digest + version).
///
/// EP-13: this is exactly the shared
/// [`UptaneMetadataSet`](kirra_release_token::uptane::UptaneMetadataSet) wire
/// shape (the same document the governor-artifact campaign channel carries) —
/// one type, so the two consumers can never drift apart.
pub type ModelMetadataBundle = kirra_release_token::uptane::UptaneMetadataSet;

/// Why the allow-list could not be derived. Every variant means: emit nothing.
#[derive(Debug)]
pub enum ModelAllowlistError {
    /// The bundle JSON did not parse.
    BundleParse(String),
    /// Trust state missing/tampered, or the floor could not be advanced.
    Trust(TrustStoreError),
    /// The metadata set failed Uptane verification (signature / expiry /
    /// rollback / chain mismatch).
    Verify(kirra_release_token::uptane::UptaneError),
}

impl std::fmt::Display for ModelAllowlistError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ModelAllowlistError::BundleParse(e) => write!(f, "metadata bundle parse: {e}"),
            ModelAllowlistError::Trust(e) => write!(f, "trust store: {e}"),
            ModelAllowlistError::Verify(e) => write!(f, "uptane verification refused: {e:?}"),
        }
    }
}
impl std::error::Error for ModelAllowlistError {}

/// Parse a [`ModelMetadataBundle`] from JSON text (fail-closed on any shape
/// mismatch — a half-parsed bundle never reaches verification).
pub fn parse_metadata_bundle(text: &str) -> Result<ModelMetadataBundle, ModelAllowlistError> {
    serde_json::from_str(text).map_err(|e| ModelAllowlistError::BundleParse(e.to_string()))
}

/// Render the env file parko launches under (systemd `EnvironmentFile=` /
/// `set -a; . file` shape). STRICT is pinned to `1` in the same artifact so an
/// empty signed manifest is deny-every-model, never enforcement-off.
#[must_use]
pub fn render_allowlist_env_file(verified: &VerifiedUpdate) -> String {
    format!(
        "# Generated by kirra-ota-ctl model-allowlist — DO NOT EDIT.\n\
         # Signed model allow-list derived from verified Uptane targets v{} \
         ({} artifact(s)).\n\
         # STRICT is pinned: an empty allow-list denies every model (deny-by-default).\n\
         KIRRA_MODEL_ALLOWLIST={}\n\
         KIRRA_MODEL_ALLOWLIST_STRICT=1\n",
        verified.targets().version,
        verified.targets().targets.len(),
        model_allowlist_env_value(verified),
    )
}

/// The full node step: load the durable trust state, run the presented bundle
/// through the fail-closed Uptane chain, ADVANCE the rollback floor durably,
/// and return the env-file text (plus the `VerifiedUpdate` for logging).
///
/// Ordering note: the floor is advanced BEFORE returning the text. If the
/// caller's subsequent file write fails, re-presenting the SAME bundle will be
/// refused as a rollback — re-publish a fresh (higher-version) metadata set to
/// retry. That bias is deliberate: a floor that lags the emitted artifact
/// would accept a replay; a floor that leads it merely costs a re-publish.
pub fn derive_model_allowlist(
    store: &UptaneTrustStore,
    bundle: &ModelMetadataBundle,
    now_ms: u64,
) -> Result<(String, VerifiedUpdate), ModelAllowlistError> {
    let state = store.load().map_err(ModelAllowlistError::Trust)?;
    let verified = verify_update(
        &state.root.meta,
        state.versions,
        now_ms,
        &bundle.timestamp,
        &bundle.timestamp_sig_b64,
        &bundle.snapshot,
        &bundle.snapshot_sig_b64,
        &bundle.targets,
        &bundle.targets_sig_b64,
    )
    .map_err(ModelAllowlistError::Verify)?;
    store
        .record_versions(verified.new_versions())
        .map_err(ModelAllowlistError::Trust)?;
    Ok((render_allowlist_env_file(&verified), verified))
}

#[cfg(test)]
mod tests {
    use super::*;
    use ed25519_dalek::SigningKey;
    use kirra_release_token::uptane::{
        author_initial_root, sign_snapshot, sign_targets, sign_timestamp, RootMetadata,
        TargetEntry, UptaneError,
    };
    use kirra_release_token::uptane::{SnapshotMetadata, TargetsMetadata, TimestampMetadata};
    use std::path::PathBuf;

    const EXP: u64 = 10_000;
    const NOW: u64 = 1_000;
    const D1: &str = "1111111111111111111111111111111111111111111111111111111111111111";
    const D2: &str = "2222222222222222222222222222222222222222222222222222222222222222";

    struct Repo {
        root_sk: SigningKey,
        targets_sk: SigningKey,
        snapshot_sk: SigningKey,
        timestamp_sk: SigningKey,
    }
    impl Repo {
        fn new() -> Self {
            Self {
                root_sk: SigningKey::from_bytes(&[1u8; 32]),
                targets_sk: SigningKey::from_bytes(&[2u8; 32]),
                snapshot_sk: SigningKey::from_bytes(&[3u8; 32]),
                timestamp_sk: SigningKey::from_bytes(&[4u8; 32]),
            }
        }
        fn root(&self) -> RootMetadata {
            RootMetadata {
                version: 1,
                expires_at_ms: EXP,
                root_key: self.root_sk.verifying_key().to_bytes(),
                targets_key: self.targets_sk.verifying_key().to_bytes(),
                snapshot_key: self.snapshot_sk.verifying_key().to_bytes(),
                timestamp_key: self.timestamp_sk.verifying_key().to_bytes(),
            }
        }
        /// A consistent signed bundle at `version` carrying `models`.
        fn bundle(&self, version: u64, models: Vec<TargetEntry>) -> ModelMetadataBundle {
            let targets = TargetsMetadata {
                version,
                expires_at_ms: EXP,
                targets: models,
            };
            let snapshot = SnapshotMetadata {
                version,
                expires_at_ms: EXP,
                targets_version: version,
            };
            let timestamp = TimestampMetadata {
                version,
                expires_at_ms: EXP,
                snapshot_version: version,
            };
            ModelMetadataBundle {
                timestamp_sig_b64: sign_timestamp(&timestamp, &self.timestamp_sk),
                snapshot_sig_b64: sign_snapshot(&snapshot, &self.snapshot_sk),
                targets_sig_b64: sign_targets(&targets, &self.targets_sk),
                timestamp,
                snapshot,
                targets,
            }
        }
    }

    fn model(digest: &str, version: &str) -> TargetEntry {
        TargetEntry {
            digest_hex: digest.into(),
            length_bytes: 1024,
            version: version.into(),
        }
    }

    fn provisioned_store(name: &str, repo: &Repo) -> (UptaneTrustStore, PathBuf) {
        let path = std::env::temp_dir().join(format!(
            "kirra_model_allowlist_{}_{name}.json",
            std::process::id()
        ));
        let _ = std::fs::remove_file(&path);
        let store = UptaneTrustStore::new(&path);
        store
            .provision(&author_initial_root(repo.root(), &repo.root_sk))
            .expect("provision anchor");
        (store, path)
    }

    /// THE DoD TEST: a signed set → the emitted env matches the manifest's
    /// digests, lowercase-canonical, with STRICT pinned.
    #[test]
    fn a_signed_manifest_emits_the_matching_env_file() {
        let repo = Repo::new();
        let (store, path) = provisioned_store("signed", &repo);
        let bundle = repo.bundle(5, vec![model(D1, "m-v1"), model(D2, "m-v2")]);

        let (text, verified) = derive_model_allowlist(&store, &bundle, NOW).expect("derive");
        assert!(
            text.contains(&format!("KIRRA_MODEL_ALLOWLIST={D1},{D2}\n")),
            "{text}"
        );
        assert!(text.contains("KIRRA_MODEL_ALLOWLIST_STRICT=1\n"), "{text}");
        assert_eq!(verified.targets().version, 5);
        // The floor advanced durably: the SAME bundle replayed is now refused.
        assert!(matches!(
            derive_model_allowlist(&store, &bundle, NOW),
            Err(ModelAllowlistError::Verify(UptaneError::RollbackAttempt(_)))
        ));
        let _ = std::fs::remove_file(&path);
    }

    /// THE DoD TEST (tamper axis): targets modified after signing → refused,
    /// nothing derived, and the trust floor does NOT advance (a later good
    /// bundle at the same version still verifies).
    #[test]
    fn a_tampered_targets_set_is_refused_and_advances_nothing() {
        let repo = Repo::new();
        let (store, path) = provisioned_store("tamper", &repo);
        let mut bundle = repo.bundle(5, vec![model(D1, "m-v1")]);
        bundle.targets.targets[0].digest_hex = D2.to_string(); // post-signing swap

        let err = derive_model_allowlist(&store, &bundle, NOW).unwrap_err();
        assert!(matches!(err, ModelAllowlistError::Verify(_)), "{err}");
        // Floor untouched: the honest v5 bundle still derives.
        let honest = repo.bundle(5, vec![model(D1, "m-v1")]);
        derive_model_allowlist(&store, &honest, NOW)
            .expect("a refused tamper must not burn the version floor");
        let _ = std::fs::remove_file(&path);
    }

    /// THE DoD TEST (deny-by-default axis): an EMPTY signed manifest emits an
    /// empty allow-list WITH strict — under parko, deny every model.
    #[test]
    fn an_empty_manifest_emits_the_strict_deny_config() {
        let repo = Repo::new();
        let (store, path) = provisioned_store("empty", &repo);
        let bundle = repo.bundle(3, vec![]);
        let (text, _) = derive_model_allowlist(&store, &bundle, NOW).expect("derive");
        assert!(text.contains("KIRRA_MODEL_ALLOWLIST=\n"), "{text}");
        assert!(text.contains("KIRRA_MODEL_ALLOWLIST_STRICT=1\n"), "{text}");
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn no_trust_state_fails_closed() {
        let repo = Repo::new();
        let path = std::env::temp_dir().join(format!(
            "kirra_model_allowlist_{}_absent.json",
            std::process::id()
        ));
        let _ = std::fs::remove_file(&path);
        let store = UptaneTrustStore::new(&path);
        let bundle = repo.bundle(1, vec![model(D1, "m-v1")]);
        assert!(matches!(
            derive_model_allowlist(&store, &bundle, NOW),
            Err(ModelAllowlistError::Trust(_))
        ));
    }

    #[test]
    fn an_expired_manifest_is_refused() {
        let repo = Repo::new();
        let (store, path) = provisioned_store("expired", &repo);
        let bundle = repo.bundle(2, vec![model(D1, "m-v1")]);
        let err = derive_model_allowlist(&store, &bundle, EXP + 1).unwrap_err();
        assert!(
            matches!(err, ModelAllowlistError::Verify(UptaneError::Expired(_))),
            "{err}"
        );
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn a_corrupt_bundle_fails_to_parse() {
        assert!(matches!(
            parse_metadata_bundle("{\"timestamp\": 42}"),
            Err(ModelAllowlistError::BundleParse(_))
        ));
    }

    #[test]
    fn bundle_round_trips_through_json() {
        let repo = Repo::new();
        let bundle = repo.bundle(9, vec![model(D1, "m-v1")]);
        let text = serde_json::to_string_pretty(&bundle).unwrap();
        let back = parse_metadata_bundle(&text).unwrap();
        assert_eq!(back.targets, bundle.targets);
        assert_eq!(back.targets_sig_b64, bundle.targets_sig_b64);
    }
}
