{{- if not .Values.admin.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-admin-token
type: Opaque
data:
  admin-token: {{ .Values.admin.token | b64enc | quote }}
{{- end }}
