#!/usr/bin/env bash
# Extract Safety traceability tags from the Governor source and emit a
# Markdown matrix to stdout (or to docs/safety/TRACEABILITY_MATRIX.md
# when --write is passed). See docs/safety/TRACEABILITY.md for the tag
# format.
#
# Recognized tag form:
#   // SAFETY: SG<n>[ SG<m>...] | REQ: <kebab-id> | TEST: <name>[,<name>...]
#
# Usage:
#   scripts/extract_safety_traceability.sh           # print to stdout
#   scripts/extract_safety_traceability.sh --write   # write to docs/safety/TRACEABILITY_MATRIX.md
#
# This is a thin convenience wrapper. The Rust CI gate at
# `src/traceability_gate.rs::ci_gate_tests` runs the same parse + assertion
# in `cargo test --lib traceability_gate`.

set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

OUT=""
if [ "${1-}" = "--write" ]; then
    OUT="docs/safety/TRACEABILITY_MATRIX.md"
fi

emit() {
    if [ -n "$OUT" ]; then
        echo "$1" >> "$OUT.tmp"
    else
        echo "$1"
    fi
}

if [ -n "$OUT" ]; then
    : > "$OUT.tmp"
fi

emit "# Occy / KIRRA — Safety Traceability Matrix"
emit ""
emit "**Doc ID:** KIRRA-OCCY-TRACE-MATRIX-001."
emit "**Generated by:** \`scripts/extract_safety_traceability.sh\` (see also"
emit "\`docs/safety/TRACEABILITY.md\` for the tag convention and"
emit "\`src/traceability_gate.rs::ci_gate_tests\` for the CI gate)."
emit "**Auto-generated from \`// SAFETY:\` annotations in \`src/\` and \`parko/crates/\`.** "
emit "Do not edit by hand — re-run the script."
emit ""
emit "---"
emit ""
emit "## Tagged enforcement sites (by SG)"
emit ""
emit "| SG | File:Line | REQ | TEST(s) |"
emit "|----|-----------|-----|---------|"

# Collect tags via grep and sort by SG then file.
# Each match line: file:lineno:// SAFETY: SGn... | REQ: ... | TEST: ...
TMP="$(mktemp)"
trap 'rm -f "$TMP" "$OUT.tmp" 2>/dev/null || true' EXIT

grep -rEn '^\s*// SAFETY:' src/ parko/crates/ 2>/dev/null | sed 's/^[[:space:]]*//' > "$TMP" || true

# Parse and emit one row per (SG × tag) combination.
awk -F'|' '
BEGIN { OFS="|" }
{
    # Split file:lineno:body off the front (file may contain colons in
    # rare cases; on this repo it does not, so the first two : delimit
    # file and line).
    pos = match($0, /:[0-9]+:/);
    if (pos == 0) next;
    pre = substr($0, 1, pos-1);
    rest_at = pos + length(substr($0, pos, match(substr($0, pos), /[0-9]+:/) + length("0") + length(":")));
    # Simpler split: file = up to first colon, then lineno = up to second colon.
    fc = index($0, ":");
    file = substr($0, 1, fc-1);
    rest = substr($0, fc+1);
    sc = index(rest, ":");
    line = substr(rest, 1, sc-1);
    body = substr(rest, sc+1);

    # body now starts with `// SAFETY: ...`
    sub(/^[[:space:]]*\/\/ SAFETY:[[:space:]]*/, "", body);

    # Split fields by |
    n = split(body, parts, /[[:space:]]*\|[[:space:]]*/);
    if (n < 3) next;

    sg_field = parts[1];
    req_field = parts[2]; sub(/^REQ:[[:space:]]*/, "", req_field);
    test_field = parts[3]; sub(/^TEST:[[:space:]]*/, "", test_field);

    # SGs are space-separated tokens like "SG3" "SG9"
    nsg = split(sg_field, sgs, /[[:space:]]+/);
    for (i = 1; i <= nsg; i++) {
        sg = sgs[i];
        if (sg !~ /^SG[1-9]$/) continue;
        printf("%s\t%s:%s\t%s\t%s\n", sg, file, line, req_field, test_field);
    }
}
' "$TMP" | sort -k1,1 -k2,2 | while IFS=$'\t' read -r sg loc req tests; do
    emit "| $sg | \`$loc\` | $req | $tests |"
done

emit ""
emit "---"
emit ""
emit "## Disposition summary"
emit ""
emit "| SG | Status | Enforcement / Reference |"
emit "|----|--------|--------------------------|"
emit "| SG1 | ENFORCED | parko-core RSS + posture_engine_v2 + parko-kirra MRC |"
emit "| SG2 | PENDING-WIRING (check built + tested in isolation; live enforcement pends Option-B trajectory wiring) | \`gateway::containment::validate_trajectory_containment\` + 11 unit tests + WCET gate; the live request-path (ProposedVehicleCommand) is per-command and does not yet carry trajectory + corridor — see Option-B wiring issue and \`docs/safety/TRACEABILITY.md\` §2 |"
emit "| SG3 | ENFORCED | \`validate_vehicle_command\` P1–P6 + \`validate_cmd_vel\` + fabric per-profile envelopes |"
emit "| SG4 | DELEGATED | Integrator perception / map prior — SEooC contract #126 |"
emit "| SG5 | DELEGATED | Integrator map prior — SEooC contract #126 |"
emit "| SG6 | DELEGATED | Impact detection PC1 (#102) — SEooC contract #126 / #127 |"
emit "| SG7 | ENFORCED + STRUCTURAL | \`classify_http_command\` + parity test in \`policy_layer::actuator_middleware_tests\` |"
emit "| SG8 | ENFORCED (Governor side) + DELEGATED (standing-MRC) | \`resolve_posture\` + LockedOut→403 + Degraded→MRC + \`AssetGovernor::evaluate_command\` + parko-kirra MRC ceiling. Standing-MRC half: SEooC contract #126. |"
emit "| SG9 | ENFORCED | NaN/Inf guard + Unknown denial + staleness fail-closed + WCET CI gate + RSS failsafe |"
emit ""

if [ -n "$OUT" ]; then
    mv "$OUT.tmp" "$OUT"
    echo "Wrote $OUT" >&2
fi
