#!/usr/bin/env python3
"""kirra-install — the platform-detecting KIRRA installer (phase B4 skeleton).

Flow (fail-closed at every hop):

  detect  → report what the hardware says (names/identifiers only)
  verify  → operator DECLARES the target platform; every mapping requirement is
            checked against detection (board mode, devices); ANY mismatch →
            refuse with the exact remediation, never a nearest-match
  install → write the two config surfaces from the mapping + selected profile
            class, delegate services to deploy/systemd/install.sh, print the
            enrollment (key ceremony) steps. `--dry-run` prints everything it
            would do; CI exercises exactly that path.

🔴 SELECT-NOT-INFER (the product's safety boundary): this tool copies reviewed
values from platform_map.toml and selects a compiled contract profile by NAME.
It never computes a safety parameter from a probe. If you are editing this
file to "derive" a wheelbase/envelope/limit from detected hardware — stop;
that is the hazard the whole design exists to prevent
(docs/product-style gap analysis; kinematics_contract.rs:647,651).

Usage:
  kirra_install.py detect
  kirra_install.py verify  --platform r2
  kirra_install.py install --platform r2 [--dry-run] [--prefix DIR]
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import tomllib

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from detect import full_report, read_board_car_type_via_vendor_lib  # noqa: E402

DEFAULT_MAP = os.path.join(HERE, "platform_map.toml")


def load_map(path: str = DEFAULT_MAP) -> dict:
    with open(path, "rb") as f:
        m = tomllib.load(f)
    if m.get("schema_version") != 1:
        raise SystemExit(f"FATAL: platform_map schema_version {m.get('schema_version')!r} "
                         f"is not 1 — refusing (fail-closed on unknown schema).")
    return m["platform"]


def verify_platform(target: str, report: dict, platforms: dict) -> list:
    """Return the list of verification FAILURES for `target` (empty = pass).

    Fail-closed: an unknown platform name, an unreadable board mode, or a
    mode/device mismatch are all failures with remediation text — never a
    guess, never a fallback to another platform's entry.
    """
    failures = []
    entry = platforms.get(target)
    if entry is None:
        return [f"unknown platform {target!r} — known: {sorted(platforms)} "
                f"(no nearest-match; add a reviewed mapping entry first)"]

    mode = report["board_mode"]
    want = entry["required_car_type"]
    if mode["car_type"] is None:
        failures.append(
            "board car-type UNREADABLE (vendor lib missing, port busy, or no "
            "board) — cannot verify the drive model; refusing. Ensure the "
            "consumer is stopped and /dev/myserial is present."
        )
    elif mode["car_type"] != want:
        failures.append(
            f"board reports car_type={mode['car_type']} ({mode['mode_name'] or 'unknown'}) "
            f"but platform {target!r} requires {want}. "
            + ("Known case: R2 hardware on the cross-labeled X3 image — flash the "
               "vendor R2 base image (a car-type flip alone breaks the drive path; "
               "see docs/hardware/HARDWARE_FINDINGS_R2X3.md)."
               if target == "r2" and mode["car_type"] == 1 else
               "Flash/configure the matching vendor base image before installing.")
        )

    motor_port = entry["motor_port"]
    port_name = os.path.basename(motor_port)
    if port_name not in report["serial_devices"]:
        failures.append(f"motor serial device {motor_port} not present")

    lidar_port = entry["lidar"]["serial_port"]
    lidar_name = os.path.basename(lidar_port)
    if lidar_name not in report["serial_devices"]:
        failures.append(
            f"lidar serial device {lidar_port} not present (expected "
            f"{entry['lidar']['model']} via {entry['lidar']['driver']})"
        )
    return failures


def render_config(target: str, entry: dict) -> dict:
    """The two config surfaces the installer populates, as {path: content}.
    Values are copied from the mapping / selected class — never computed."""
    lidar = entry["lidar"]
    verifier_env = (
        "# generated by kirra-install — platform: {p}\n"
        "# Safety numbers come from the compiled contract profile for this class;\n"
        "# this file only SELECTS it (select-not-infer).\n"
        "KIRRA_VEHICLE_CLASS={cls}\n"
    ).format(p=target, cls=entry["profile_class"])
    robot_env = (
        "# generated by kirra-install — platform: {p}\n"
        "KIRRA_MOTOR_PORT={motor}\n"
        "KIRRA_EXPECTED_CAR_TYPE={ct}\n"
        "# Lidar ({model}) — driver {driver} @ {baud}, {qos} QoS, topic {topic}\n"
        "KIRRA_LIDAR_SERIAL_PORT={lport}\n"
        "KIRRA_LIDAR_BAUD={baud}\n"
        "# Demo envelope + keys are DEPLOYMENT inputs, deliberately not written\n"
        "# here: envelope values must match the selected class review, and keys\n"
        "# come from the enrollment ceremony (never a well-known dev seed).\n"
    ).format(p=target, motor=entry["motor_port"], ct=entry["required_car_type"],
             model=lidar["model"], driver=lidar["driver"], baud=lidar["baud"],
             qos=lidar["qos"], topic=lidar["scan_topic"], lport=lidar["serial_port"])
    return {
        "etc/kirra/platform.env": verifier_env,
        "etc/kirra/robot.env": robot_env,
    }


def cmd_install(target: str, report: dict, platforms: dict,
                dry_run: bool, prefix: str) -> int:
    failures = verify_platform(target, report, platforms)
    if failures:
        print("VERIFY FAILED — install refused (fail-closed):")
        for f in failures:
            print(f"  ✗ {f}")
        return 1
    entry = platforms[target]
    files = render_config(target, entry)
    steps = [
        f"write {len(files)} config file(s) under {prefix or '/'}",
        "run deploy/systemd/install.sh (binaries, units, secrets — existing installer)",
        "ENROLLMENT (operator ceremony, not automated): provision the governor "
        "signing key (KIRRA_GOVERNOR_SIGNING_KEY_SOURCE=file:…), pin the consumer "
        "verifying key (kirra-consumer-ctl enroll), node attestation (kirra-ota-ctl enroll)",
        f"lidar driver: {entry['lidar']['driver']} @ {entry['lidar']['baud']} on "
        f"{entry['lidar']['serial_port']} ({entry['lidar']['qos']} QoS)",
        f"cameras: {entry['cameras']['policy']} — detected: {report['cameras'] or 'none'}",
        "post-install acceptance: robot/ffi_smoke_test.py + robot/teardown_smoke_test.py, "
        "then the ELEVATED first-run suite before any floor contact",
    ]
    print(f"install plan for platform {target!r}:")
    for s in steps:
        print(f"  • {s}")
    for rel, content in files.items():
        path = os.path.join(prefix, rel) if prefix else "/" + rel
        if dry_run:
            print(f"\n--- would write {path} ---\n{content}")
        else:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
            print(f"wrote {path}")
    if dry_run:
        print("\nDRY RUN — nothing written/executed.")
    else:
        print("\nConfig written. Services + enrollment are the next operator steps "
              "(see docs/hardware/R2_GOLDEN_BUILD.md).")
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(prog="kirra-install")
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("detect")
    for name in ("verify", "install"):
        p = sub.add_parser(name)
        p.add_argument("--platform", required=True)
        if name == "install":
            p.add_argument("--dry-run", action="store_true")
            p.add_argument("--prefix", default="")
    args = ap.parse_args(argv)

    def reader():
        return read_board_car_type_via_vendor_lib(port="/dev/myserial")

    report = full_report(reader)
    platforms = load_map()

    if args.cmd == "detect":
        print(json.dumps(report, indent=2))
        return 0
    if args.cmd == "verify":
        failures = verify_platform(args.platform, report, platforms)
        if failures:
            print(f"VERIFY FAILED for {args.platform!r}:")
            for f in failures:
                print(f"  ✗ {f}")
            return 1
        print(f"VERIFY OK — hardware matches platform {args.platform!r}")
        return 0
    return cmd_install(args.platform, report, platforms, args.dry_run, args.prefix)


if __name__ == "__main__":
    sys.exit(main())
